#!/bin/bash

#P_FDF='/Users/evogel/42Projects/fdf_team/'
P_FDF='/Users/brichard/Projects/FilDeFer/fdf/'

algood()
{
	echo -n All Good!
	echo -n .
	sleep 1
	echo -n .
	sleep 1
	echo .
}


clo()
{
	tput clear
	read -p "Where is it? " add
	read -p "Where does it go? " loc
	git clone $add $loc
}

pu()
{
	tput clear
	git add ./
	git status
	read -p "On commit? y/n "
	case $REPLY in
		"y")
			read -p "commit: "
			git commit -m "$REPLY"
			git push
			exit 0;
			;;
		"n")
			gc
			;;
		*)
			echo "Ah non, ca marche pas ca: '$REPLY'"
			;;
	esac
}

gc()
{
	tput clear
	select choice in "git clone" "git push" "exit"
	do
		case $REPLY in
			1)
				clo
				;;
			2)
				pu
				;;
			3)
				echo "Bye bye! ;)"
				exit 0
				;;
			*)
				echo Wrong answer!
				;;
		esac
	done
}

tput clear
if [ "$1" = "re" ]; then
	make re -C $P_FDF
	if [ $? -eq 0 ]; then
		algood
		$P_FDF/fdf $2
	fi
elif [ "$1" = "git" ]; then 
	gc
else
	make -C $P_FDF
	if [ $? -eq 0 ]; then
		algood
		$P_FDF/fdf $1
	fi
fi
